### ISSUE TITLE
Installing without a Service Pack

### ISSUE THREAD

**Issue by mkszuba** [voxpupuli/puppet-msoffice#50]
Hello,

How exactly should one request installation of Office for a version which does not have any Service Packs available, e.g. 2013 or 2016? At the moment I try to do it like this:

`msoffice { 'Office 2013':
    ensure          => present,
    version         => '2013',
    edition         => 'Professional Plus',
    sp              => '0',
    arch            => 'x64',
    lang_code       => 'de-de',
    deployment_root => 'foo',
    license_key     => 'bar',
    products        => ['Word'],
}
`

because not having set sp at all produced an error. However, when ${sp} is set to 0 I get an error from msoffice::servicepack "the service pack specified does not match 1-3". An interesting thing is, this happens even when Puppet tries to install Office on a system which doesn't have it - even though according to the documentation this module should only attempt to install SPs and LIPs once Office has already been installed. I've had a look at the code but it only got me more confused: unless I have misunderstood, it seems SPs and LIPs are installed when the ensure option is set to 'present', regardless of whether Office has actually been installed or not, which is at odds with documentation (although it does explain why I see the problem).

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.9.3
- Ruby: 2.1.5p273
- Module version: Git commit 05d4af1c48bc8de5119d3d8f751456a7267240dd (i.e. master as of 2017-04-25)

**Comment by Johnz216** [comment]
Hey, I was having the same issue with the service pack issue. It turns out that in serivcepack.pp is looking for numbers 1-3 on line Line 44:23. I made the following changes:

  validate_re($sp,'^([**0**-3])$','The service pack specified does not match **0**-3')

If you look at params.pp, you can see that some that **$office_version** have the service pack **0** in them.

After that change was made I was able to deploy my package successfully after making sure I pointed to the correct deployment root.

I hope that helps you out! Just figured it out today :)

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
